# Generated by Django 4.2.4 on 2023-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="images/")),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reduction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("categorie", models.CharField(max_length=100)),
                ("etat", models.CharField(max_length=100)),
            ],
        ),
    ]
