# Generated by Django 4.2.4 on 2023-08-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="image",
            field=models.ImageField(upload_to="static/images/"),
        ),
    ]
