# Generated by Django 4.2.4 on 2023-08-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_itempanier_panier_itempanier_panier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("reduction", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
