# Generated by Django 4.2.4 on 2023-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_total_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="total",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
