# Generated by Django 4.2.4 on 2023-08-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_total_value_total_total_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="media/images/")),
            ],
        ),
    ]
